config/routes.rb
JournalEntry::Application.routes.draw do

  resources :entries
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_uniqueness_of :name
  validates :name, length: { minimum: 1 }

  has_many :entries,
    inverse_of: :category
end

app/models/entry.rb
class Entry < ActiveRecord::Base

  validates :title, length: { minimum: 1 }
  validates :description, length: { minimum: 1 }
  validates_numericality_of :category_id, only_integer: true, allow_nil: true

  belongs_to :category,
    inverse_of: :entry

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
  end

  def new
    @category = Category.new
  end


  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    @category = Category.find_by(id: params[:id])
  end

  def update
    @category = Category.find_by(id: params[:id])
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was updated!'
    else
      render action: 'edit'
    end
  end

  def destroy
    @category = Category.find_by(id: params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @entries = Entry.order(created_at: :desc)
  end

  def show
    @entry = Entry.find_by(id: params[:id])
  end

  def new
    @entry = Entry.new
  end


  def create
    @entry = Entry.new(entry_params)
    @category = Category.find_by(id: params[:entry][:category_id])

    @entry.category = @category
    if @entry.save
      redirect_to @entry, notice: 'Entry was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    @entry = Entry.find_by(id: params[:id])
  end

  def update
    @entry = Entry.find_by(id: params[:id])
    if @entry.update(entry_params)
      redirect_to @entry, notice: 'Entry was update!!'
    else
      render action: 'edit'
    end
  end

  def destroy
    @entry = Entry.find_by(id: params[:id])
    @entry.destroy
    redirect_to entries_path
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :name %>
  <%= f.submit "Create Category" %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <%= link_to category.name, category %>
  <%= link_to "edit", edit_category_path(category) %>
  <%= link_to "destroy", category, method: :delete, data: { confirm: 'Are you sure?' } %><br>
<% end %>
<%= link_to "new", new_category_path %><br>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :title %><br>
  <%= f.text_area :description %><br>
  <% Category.all.each do |cat| %>
    <%= f.radio_button(:category_id, cat.id) %>
    <%= f.label(:category, cat.name) %>
  <% end %>
  <%= f.submit "Submit Entry" %>
<% end %>

app/views/entries/edit.html.erb
<%= render 'form' %>

app/views/entries/index.html.erb
<% @entries.each do |entry| %>
  <%= link_to entry.title, entry %>
  <%= entry.created_at %>
  <%= link_to "edit", edit_entry_path(entry) %>
  <%= link_to "destroy", entry, method: :delete, data: { confirm: 'Are you sure?' } %><br>
<% end %>
<%= link_to "new", new_entry_path %><br>

app/views/entries/new.html.erb
<%= render 'form' %>

app/views/entries/show.html.erb
<h1><%= @entry.title %></h1>
<p><%= @entry.description %></p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JournalEntry</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>